[package]
name = "genevo"
version = "0.1.4"
authors = ["haraldmaida"]
license = "MIT/Apache-2.0"
description = """
genevo provides building blocks to run simulations of optimization and search problems using
genetic algorithms (GA).

Execute genetic algorithm (GA) simulations in a customizable and extensible way.
"""
keywords = ["genetic", "evolutionary", "algorithm"]
repository = "https://github.com/innoave/genevo"
documentation = "https://docs.rs/genevo"
#homepage = "https://innoave.github.io/genevo"
readme = "README.md"

[lib]
name = "genevo"
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
fixedbitset = "0.1"
log = "0.4"
rand = "0.3"
rayon = "1.0"
xorshift = "0.1"

[dev-dependencies]
galvanic-assert = "0.8"
quickcheck = "0.8"
#log4rs = "0.8"

[[example]]
name = "monkeys"
path = "examples/monkeys/main.rs"

[[example]]
name = "queens"
path = "examples/queens/main.rs"
